on:
  workflow_dispatch:
jobs:
  pyembed:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: "--all-features --manifest-path pyembed/Cargo.toml"
