on:
  workflow_dispatch:
jobs:
  sphinx:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - python-oxidized-importer/docs
          - pyembed/docs
          - pyoxy/docs
          - tugger/docs
          - docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run Sphinx
        run: |
          python3.9 -m pip install Sphinx==4.2.0
          make -C ${{ matrix.dir }} html
